#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                        0
#define TRAINER_SAWYER_1                    1
#define TRAINER_SAWYER_2                    2
#define TRAINER_GRUNT_AQUA_HIDEOUT_1        3
#define TRAINER_GRUNT_AQUA_HIDEOUT_2        4
#define TRAINER_GRUNT_AQUA_HIDEOUT_3        5
#define TRAINER_GRUNT_AQUA_HIDEOUT_4        6
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_1     7
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2     8
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3     9
#define TRAINER_GABRIELLE_1                 10
#define TRAINER_GABRIELLE_2                 11
#define TRAINER_GRUNT_PETALBURG_WOODS       12
#define TRAINER_MARCEL                      13
#define TRAINER_ALBERTO                     14
#define TRAINER_ED                          15
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4     16
#define TRAINER_DECLAN                      17
#define TRAINER_GRUNT_RUSTURF_TUNNEL        18
#define TRAINER_GRUNT_WEATHER_INST_1        19
#define TRAINER_GRUNT_WEATHER_INST_2        20
#define TRAINER_GRUNT_WEATHER_INST_3        21
#define TRAINER_GRUNT_MUSEUM_1              22
#define TRAINER_GRUNT_MUSEUM_2              23
#define TRAINER_GRUNT_SPACE_CENTER_1        24
#define TRAINER_GRUNT_MT_PYRE_1             25
#define TRAINER_GRUNT_MT_PYRE_2             26
#define TRAINER_GRUNT_MT_PYRE_3             27
#define TRAINER_GRUNT_WEATHER_INST_4        28
#define TRAINER_GRUNT_AQUA_HIDEOUT_5        29
#define TRAINER_GRUNT_AQUA_HIDEOUT_6        30
#define TRAINER_FREDRICK                    31
#define TRAINER_MATT                        32
#define TRAINER_ZANDER                      33
#define TRAINER_SHELLY_WEATHER_INSTITUTE    34
#define TRAINER_SHELLY_SEAFLOOR_CAVERN      35
#define TRAINER_ARCHIE                      36
#define TRAINER_LEAH                        37
#define TRAINER_DAISY                       38
#define TRAINER_ROSE_1                      39
#define TRAINER_ROSE_2                      40
#define TRAINER_FELIX                       41
#define TRAINER_VIOLET                      42
#define TRAINER_DUSTY_1                     43
#define TRAINER_DUSTY_2                     44
#define TRAINER_CHIP                        45
#define TRAINER_FOSTER                      46
#define TRAINER_GABBY_AND_TY_1              47
#define TRAINER_GABBY_AND_TY_2              48
#define TRAINER_GABBY_AND_TY_3              49
#define TRAINER_GABBY_AND_TY_4              50
#define TRAINER_GABBY_AND_TY_5              51
#define TRAINER_GABBY_AND_TY_6              52
#define TRAINER_LOLA_1                      53
#define TRAINER_LOLA_2                      54
#define TRAINER_AUSTINA                     55
#define TRAINER_GWEN                        56
#define TRAINER_RICKY_1                     57
#define TRAINER_RICKY_2                     58
#define TRAINER_SIMON                       59
#define TRAINER_CHARLIE                     60
#define TRAINER_RANDALL                     61
#define TRAINER_PARKER                      62
#define TRAINER_GEORGE                      63
#define TRAINER_BERKE                       64
#define TRAINER_BRAXTON                     65
#define TRAINER_VINCENT                     66
#define TRAINER_LEROY                       67
#define TRAINER_WILTON_1                    68
#define TRAINER_WILTON_2                    69
#define TRAINER_EDGAR                       70
#define TRAINER_ALBERT                      71
#define TRAINER_SAMUEL                      72
#define TRAINER_VITO                        73
#define TRAINER_OWEN                        74
#define TRAINER_WARREN                      75
#define TRAINER_MARY                        76
#define TRAINER_ALEXIA                      77
#define TRAINER_JODY                        78
#define TRAINER_WENDY                       79
#define TRAINER_KEIRA                       80
#define TRAINER_BROOKE_1                    81
#define TRAINER_BROOKE_2                    82
#define TRAINER_JENNIFER                    83
#define TRAINER_HOPE                        84
#define TRAINER_SHANNON                     85
#define TRAINER_MICHELLE                    86
#define TRAINER_CAROLINE                    87
#define TRAINER_JULIE                       88
#define TRAINER_PATRICIA                    89
#define TRAINER_KINDRA                      90
#define TRAINER_TAMMY                       91
#define TRAINER_VALERIE_1                   92
#define TRAINER_VALERIE_2                   93
#define TRAINER_TASHA                       94
#define TRAINER_CINDY_1                     95
#define TRAINER_CINDY_2                     96
#define TRAINER_DAPHNE                      97
#define TRAINER_GRUNT_SPACE_CENTER_2        98
#define TRAINER_BRIANNA                     99
#define TRAINER_NAOMI                       100
#define TRAINER_MELISSA                     101
#define TRAINER_SHEILA                      102
#define TRAINER_SHIRLEY                     103
#define TRAINER_JESSICA_1                   104
#define TRAINER_JESSICA_2                   105
#define TRAINER_CONNIE                      106
#define TRAINER_BRIDGET                     107
#define TRAINER_OLIVIA                      108
#define TRAINER_TIFFANY                     109
#define TRAINER_WINSTON_1                   110
#define TRAINER_WINSTON_2                   111
#define TRAINER_MOLLIE                      112
#define TRAINER_GARRET                      113
#define TRAINER_STEVE_1                     114
#define TRAINER_STEVE_2                     115
#define TRAINER_THALIA_1                    116
#define TRAINER_THALIA_2                    117
#define TRAINER_MARK                        118
#define TRAINER_GRUNT_MT_CHIMNEY_1          119
#define TRAINER_LUIS                        120
#define TRAINER_DOMINIK                     121
#define TRAINER_DOUGLAS                     122
#define TRAINER_DARRIN                      123
#define TRAINER_TONY_1                      124
#define TRAINER_TONY_2                      125
#define TRAINER_JEROME                      126
#define TRAINER_MATTHEW                     127
#define TRAINER_DAVID                       128
#define TRAINER_SPENCER                     129
#define TRAINER_ROLAND                      130
#define TRAINER_NOLEN                       131
#define TRAINER_STAN                        132
#define TRAINER_BARRY                       133
#define TRAINER_DEAN                        134
#define TRAINER_RODNEY                      135
#define TRAINER_RICHARD                     136
#define TRAINER_HERMAN                      137
#define TRAINER_SANTIAGO                    138
#define TRAINER_GILBERT                     139
#define TRAINER_FRANKLIN                    140
#define TRAINER_KEVIN                       141
#define TRAINER_JACK                        142
#define TRAINER_DUDLEY                      143
#define TRAINER_CHAD                        144
#define TRAINER_TAKAO                       145
#define TRAINER_HITOSHI                     146
#define TRAINER_KIYO                        147
#define TRAINER_KOICHI                      148
#define TRAINER_NOB_1                       149
#define TRAINER_NOB_2                       150
#define TRAINER_YUJI                        151
#define TRAINER_DAISUKE                     152
#define TRAINER_ATSUSHI                     153
#define TRAINER_KIRK                        154
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        155
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        156
#define TRAINER_SHAWN                       157
#define TRAINER_FERNANDO_1                  158
#define TRAINER_FERNANDO_2                  159
#define TRAINER_DALTON_1                    160
#define TRAINER_DALTON_2                    161
#define TRAINER_COLE                        162
#define TRAINER_JEFF                        163
#define TRAINER_AXLE                        164
#define TRAINER_JACE                        165
#define TRAINER_KEEGAN                      166
#define TRAINER_BERNIE_1                    167
#define TRAINER_BERNIE_2                    168
#define TRAINER_DREW                        169
#define TRAINER_BEAU                        170
#define TRAINER_LARRY                       171
#define TRAINER_SHANE                       172
#define TRAINER_JUSTIN                      173
#define TRAINER_ETHAN_1                     174
#define TRAINER_ETHAN_2                     175
#define TRAINER_AUTUMN                      176
#define TRAINER_TRAVIS                      177
#define TRAINER_BRENT                       178
#define TRAINER_DONALD                      179
#define TRAINER_TAYLOR                      180
#define TRAINER_JEFFREY_1                   181
#define TRAINER_JEFFREY_2                   182
#define TRAINER_DEREK                       183
#define TRAINER_EDWARD                      184
#define TRAINER_PRESTON                     185
#define TRAINER_VIRGIL                      186
#define TRAINER_BLAKE                       187
#define TRAINER_WILLIAM                     188
#define TRAINER_JOSHUA                      189
#define TRAINER_CAMERON_1                   190
#define TRAINER_CAMERON_2                   191
#define TRAINER_JACLYN                      192
#define TRAINER_HANNAH                      193
#define TRAINER_SAMANTHA                    194
#define TRAINER_MAURA                       195
#define TRAINER_KAYLA                       196
#define TRAINER_ALEXIS                      197
#define TRAINER_JACKI_1                     198
#define TRAINER_JACKI_2                     199
#define TRAINER_WALTER_1                    200
#define TRAINER_WALTER_2                    201
#define TRAINER_MICAH                       202
#define TRAINER_THOMAS                      203
#define TRAINER_SIDNEY                      204
#define TRAINER_PHOEBE                      205
#define TRAINER_GLACIA                      206
#define TRAINER_DRAKE                       207
#define TRAINER_ROXANNE_1                   208
#define TRAINER_ROXANNE_2                   209
#define TRAINER_BRAWLY_1                    210
#define TRAINER_BRAWLY_2                    211
#define TRAINER_WATTSON_1                   212
#define TRAINER_WATTSON_2                   213
#define TRAINER_FLANNERY_1                  214
#define TRAINER_FLANNERY_2                  215
#define TRAINER_NORMAN_1                    216
#define TRAINER_NORMAN_2                    217
#define TRAINER_WINONA_1                    218
#define TRAINER_WINONA_2                    219
#define TRAINER_TATE_AND_LIZA_1             220
#define TRAINER_TATE_AND_LIZA_2             221
#define TRAINER_JUAN_1                      222
#define TRAINER_JUAN_2                      223
#define TRAINER_JERRY_1                     224
#define TRAINER_JERRY_2                     225
#define TRAINER_TED                         226
#define TRAINER_PAUL                        227
#define TRAINER_KAREN_1                     228
#define TRAINER_KAREN_2                     229
#define TRAINER_GEORGIA                     230
#define TRAINER_KATE_AND_JOY                231
#define TRAINER_ANNA_AND_MEG_1              232
#define TRAINER_ANNA_AND_MEG_2              233
#define TRAINER_VICTOR                      234
#define TRAINER_MIGUEL_1                    235
#define TRAINER_MIGUEL_2                    236
#define TRAINER_COLTON                      237
#define TRAINER_VICTORIA                    238
#define TRAINER_VANESSA                     239
#define TRAINER_BETHANY                     240
#define TRAINER_ISABEL_1                    241
#define TRAINER_ISABEL_2                    242
#define TRAINER_TIMOTHY_1                   243
#define TRAINER_TIMOTHY_2                   244
#define TRAINER_VICKY                       245
#define TRAINER_SHELBY_1                    246
#define TRAINER_SHELBY_2                    247
#define TRAINER_CALVIN_1                    248
#define TRAINER_CALVIN_2                    249
#define TRAINER_BILLY                       250
#define TRAINER_JOSH                        251
#define TRAINER_TOMMY                       252
#define TRAINER_JOEY                        253
#define TRAINER_BEN                         254
#define TRAINER_QUINCY                      255
#define TRAINER_KATELYNN                    256
#define TRAINER_JAYLEN                      257
#define TRAINER_DILLON                      258
#define TRAINER_EDDIE                       259
#define TRAINER_ALLEN                       260
#define TRAINER_TIMMY                       261
#define TRAINER_WALLACE                     262
#define TRAINER_ANDREW                      263
#define TRAINER_IVAN                        264
#define TRAINER_CLAUDE                      265
#define TRAINER_ELLIOT_1                    266
#define TRAINER_ELLIOT_2                    267
#define TRAINER_NED                         268
#define TRAINER_DALE                        269
#define TRAINER_NOLAN                       270
#define TRAINER_BARNY                       271
#define TRAINER_WADE                        272
#define TRAINER_CARTER                      273
#define TRAINER_RONALD                      274
#define TRAINER_JACOB                       275
#define TRAINER_ANTHONY                     276
#define TRAINER_BENJAMIN_1                  277
#define TRAINER_BENJAMIN_2                  278
#define TRAINER_ABIGAIL_1                   279
#define TRAINER_ABIGAIL_2                   280
#define TRAINER_JASMINE                     281
#define TRAINER_DYLAN_1                     282
#define TRAINER_DYLAN_2                     283
#define TRAINER_MARIA_1                     284
#define TRAINER_MARIA_2                     285
#define TRAINER_CAMDEN                      286
#define TRAINER_DEMETRIUS                   287
#define TRAINER_ISAIAH_1                    288
#define TRAINER_ISAIAH_2                    289
#define TRAINER_PABLO_1                     290
#define TRAINER_PABLO_2                     291
#define TRAINER_CHASE                       292
#define TRAINER_ISOBEL                      293
#define TRAINER_DONNY                       294
#define TRAINER_TALIA                       295
#define TRAINER_KATELYN_1                   296
#define TRAINER_KATELYN_2                   297
#define TRAINER_ALLISON                     298
#define TRAINER_NICOLAS_1                   299
#define TRAINER_NICOLAS_2                   300
#define TRAINER_AARON                       301
#define TRAINER_PERRY                       302
#define TRAINER_HUGH                        303
#define TRAINER_PHIL                        304
#define TRAINER_JARED                       305
#define TRAINER_HUMBERTO                    306
#define TRAINER_PRESLEY                     307
#define TRAINER_EDWARDO                     308
#define TRAINER_COLIN                       309
#define TRAINER_ROBERT_1                    310
#define TRAINER_ROBERT_2                    311
#define TRAINER_BENNY                       312
#define TRAINER_CHESTER                     313
#define TRAINER_ALEX                        314
#define TRAINER_BECK                        315
#define TRAINER_YASU                        316
#define TRAINER_TAKASHI                     317
#define TRAINER_DIANNE                      318
#define TRAINER_JANI                        319
#define TRAINER_LAO_1                       320
#define TRAINER_LAO_2                       321
#define TRAINER_LUNG                        322
#define TRAINER_JOCELYN                     323
#define TRAINER_LAURA                       324
#define TRAINER_CYNDY_1                     325
#define TRAINER_CYNDY_2                     326
#define TRAINER_CORA                        327
#define TRAINER_PAULA                       328
#define TRAINER_MADELINE_1                  329
#define TRAINER_MADELINE_2                  330
#define TRAINER_CLARISSA                    331
#define TRAINER_ANGELICA                    332
#define TRAINER_BEVERLY                     333
#define TRAINER_IMANI                       334
#define TRAINER_KYLA                        335
#define TRAINER_DENISE                      336
#define TRAINER_BETH                        337
#define TRAINER_TARA                        338
#define TRAINER_MISSY                       339
#define TRAINER_ALICE                       340
#define TRAINER_JENNY_1                     341
#define TRAINER_JENNY_2                     342
#define TRAINER_GRACE                       343
#define TRAINER_TANYA                       344
#define TRAINER_SHARON                      345
#define TRAINER_NIKKI                       346
#define TRAINER_BRENDA                      347
#define TRAINER_KATIE                       348
#define TRAINER_SUSIE                       349
#define TRAINER_KARA                        350
#define TRAINER_DANA                        351
#define TRAINER_SIENNA                      352
#define TRAINER_DEBRA                       353
#define TRAINER_LINDA                       354
#define TRAINER_KAYLEE                      355
#define TRAINER_LAUREL                      356
#define TRAINER_CARLEE                      357
#define TRAINER_HEIDI                       358
#define TRAINER_BECKY                       359
#define TRAINER_CAROL                       360
#define TRAINER_NANCY                       361
#define TRAINER_MARTHA                      362
#define TRAINER_DIANA_1                     363
#define TRAINER_DIANA_2                     364
#define TRAINER_CEDRIC                      365
#define TRAINER_IRENE                       366
#define TRAINER_AMY_AND_LIV_1               367
#define TRAINER_AMY_AND_LIV_2               368
#define TRAINER_GINA_AND_MIA_1              369
#define TRAINER_GINA_AND_MIA_2              370
#define TRAINER_MIU_AND_YUKI                371
#define TRAINER_HUEY                        372
#define TRAINER_EDMOND                      373
#define TRAINER_ERNEST_1                    374
#define TRAINER_ERNEST_2                    375
#define TRAINER_DWAYNE                      376
#define TRAINER_PHILLIP                     377
#define TRAINER_LEONARD                     378
#define TRAINER_DUNCAN                      379
#define TRAINER_ELI                         380
#define TRAINER_ANNIKA                      381
#define TRAINER_JAZMYN                      382
#define TRAINER_JONAS                       383
#define TRAINER_KAYLEY                      384
#define TRAINER_AURON                       385
#define TRAINER_KELVIN                      386
#define TRAINER_MARLEY                      387
#define TRAINER_REYNA                       388
#define TRAINER_HUDSON                      389
#define TRAINER_CONOR                       390
#define TRAINER_EDWIN_1                     391
#define TRAINER_EDWIN_2                     392
#define TRAINER_HECTOR                      393
#define TRAINER_TABITHA_MOSSDEEP            394
#define TRAINER_WALLY_MAUVILLE              395
#define TRAINER_WALLY_VR_1                  396
#define TRAINER_WALLY_VR_2                  397
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    398
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     399
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    400
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    401
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     402
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   403
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    404
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   405
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   406
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    407
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   408
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    409
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   410
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   411
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    412
#define TRAINER_BRENDAN_PLACEHOLDER         413
#define TRAINER_MAY_ROUTE_103_MUDKIP        414
#define TRAINER_MAY_RUSTBORO_MUDKIP         415
#define TRAINER_MAY_ROUTE_110_MUDKIP        416
#define TRAINER_MAY_ROUTE_119_MUDKIP        417
#define TRAINER_MAY_LILYCOVE_MUDKIP         418
#define TRAINER_MAY_ROUTE_103_TREECKO       419
#define TRAINER_MAY_RUSTBORO_TREECKO        420
#define TRAINER_MAY_ROUTE_110_TREECKO       421
#define TRAINER_MAY_ROUTE_119_TREECKO       422
#define TRAINER_MAY_LILYCOVE_TREECKO        423
#define TRAINER_MAY_ROUTE_103_TORCHIC       424
#define TRAINER_MAY_RUSTBORO_TORCHIC        425
#define TRAINER_MAY_ROUTE_110_TORCHIC       426
#define TRAINER_MAY_ROUTE_119_TORCHIC       427
#define TRAINER_MAY_LILYCOVE_TORCHIC        428
#define TRAINER_MAY_PLACEHOLDER             429
#define TRAINER_ISAAC_1                     430
#define TRAINER_ISAAC_2                     431
#define TRAINER_DAVIS                       432
#define TRAINER_MITCHELL                    433
#define TRAINER_LYDIA_1                     434
#define TRAINER_LYDIA_2                     435
#define TRAINER_HALLE                       436
#define TRAINER_GARRISON                    437
#define TRAINER_JACKSON_1                   438
#define TRAINER_JACKSON_2                   439
#define TRAINER_LORENZO                     440
#define TRAINER_SEBASTIAN                   441
#define TRAINER_CATHERINE_1                 442
#define TRAINER_CATHERINE_2                 443
#define TRAINER_JENNA                       444
#define TRAINER_SOPHIA                      445
#define TRAINER_JULIO                       446
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     447
#define TRAINER_GRUNT_UNUSED                448
#define TRAINER_GRUNT_MT_PYRE_4             449
#define TRAINER_GRUNT_JAGGED_PASS           450
#define TRAINER_MARC                        451
#define TRAINER_BRENDEN                     452
#define TRAINER_LILITH                      453
#define TRAINER_CRISTIAN                    454
#define TRAINER_SYLVIA                      455
#define TRAINER_LEONARDO                    456
#define TRAINER_ATHENA                      457
#define TRAINER_HARRISON                    458
#define TRAINER_GRUNT_MT_CHIMNEY_2          459
#define TRAINER_CLARENCE                    460
#define TRAINER_TERRY                       461
#define TRAINER_NATE                        462
#define TRAINER_KATHLEEN                    463
#define TRAINER_CLIFFORD                    464
#define TRAINER_NICHOLAS                    465
#define TRAINER_GRUNT_SPACE_CENTER_3        466
#define TRAINER_GRUNT_SPACE_CENTER_4        467
#define TRAINER_GRUNT_SPACE_CENTER_5        468
#define TRAINER_GRUNT_SPACE_CENTER_6        469
#define TRAINER_GRUNT_SPACE_CENTER_7        470
#define TRAINER_MACEY                       471
#define TRAINER_PAXTON                      472
#define TRAINER_ISABELLA                    473
#define TRAINER_GRUNT_WEATHER_INST_5        474
#define TRAINER_TABITHA_MT_CHIMNEY          475
#define TRAINER_JONATHAN                    476
#define TRAINER_MAXIE_MAGMA_HIDEOUT         477
#define TRAINER_MAXIE_MT_CHIMNEY            478
#define TRAINER_TIANA                       479
#define TRAINER_HALEY_1                     480
#define TRAINER_HALEY_2                     481
#define TRAINER_JANICE                      482
#define TRAINER_VIVI                        483
#define TRAINER_SALLY                       484
#define TRAINER_ROBIN                       485
#define TRAINER_ANDREA                      486
#define TRAINER_CRISSY                      487
#define TRAINER_RICK                        488
#define TRAINER_LYLE                        489
#define TRAINER_JOSE                        490
#define TRAINER_DOUG                        491
#define TRAINER_GREG                        492
#define TRAINER_KENT                        493
#define TRAINER_JAMES_1                     494
#define TRAINER_JAMES_2                     495
#define TRAINER_BRICE                       496
#define TRAINER_TRENT_1                     497
#define TRAINER_TRENT_2                     498
#define TRAINER_LENNY                       499
#define TRAINER_LUCAS_1                     500
#define TRAINER_LUCAS_2                     501
#define TRAINER_ALAN                        502
#define TRAINER_CLARK                       503
#define TRAINER_ERIC                        504
#define TRAINER_MIKE_1                      505
#define TRAINER_MIKE_2                      506
#define TRAINER_DEZ_AND_LUKE                507
#define TRAINER_LEA_AND_JED                 508
#define TRAINER_KIRA_AND_DAN_1              509
#define TRAINER_KIRA_AND_DAN_2              510
#define TRAINER_JOHANNA                     511
#define TRAINER_GERALD                      512
#define TRAINER_VIVIAN                      513
#define TRAINER_DANIELLE                    514
#define TRAINER_HIDEO                       515
#define TRAINER_KEIGO                       516
#define TRAINER_RILEY                       517
#define TRAINER_FLINT                       518
#define TRAINER_ASHLEY                      519
#define TRAINER_JONAH                       520
#define TRAINER_HENRY                       521
#define TRAINER_ROGER                       522
#define TRAINER_ALEXA                       523
#define TRAINER_RUBEN                       524
#define TRAINER_KOJI_1                      525
#define TRAINER_KOJI_2                      526
#define TRAINER_WAYNE                       527
#define TRAINER_AIDAN                       528
#define TRAINER_REED                        529
#define TRAINER_TISHA                       530
#define TRAINER_TORI_AND_TIA                531
#define TRAINER_KIM_AND_IRIS                532
#define TRAINER_TYRA_AND_IVY                533
#define TRAINER_MEL_AND_PAUL                534
#define TRAINER_JOHN_AND_JAY_1              535
#define TRAINER_JOHN_AND_JAY_2              536
#define TRAINER_RELI_AND_IAN                537
#define TRAINER_LILA_AND_ROY_1              538
#define TRAINER_LILA_AND_ROY_2              539
#define TRAINER_LISA_AND_RAY                540
#define TRAINER_CHRIS                       541
#define TRAINER_DAWSON                      542
#define TRAINER_SARAH                       543
#define TRAINER_DARIAN                      544
#define TRAINER_HAILEY                      545
#define TRAINER_CHANDLER                    546
#define TRAINER_KALEB                       547
#define TRAINER_JOSEPH                      548
#define TRAINER_ALYSSA                      549
#define TRAINER_MARCOS                      550
#define TRAINER_RHETT                       551
#define TRAINER_TYRON                       552
#define TRAINER_CELINA                      553
#define TRAINER_BIANCA                      554
#define TRAINER_HAYDEN                      555
#define TRAINER_SOPHIE                      556
#define TRAINER_COBY                        557
#define TRAINER_LAWRENCE                    558
#define TRAINER_WYATT                       559
#define TRAINER_ANGELINA                    560
#define TRAINER_KAI                         561
#define TRAINER_CHARLOTTE                   562
#define TRAINER_DEANDRE                     563
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       564
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       565
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       566
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       567
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       568
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       569
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       570
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       571
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       572
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      573
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      574
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      575
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      576
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      577
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      578
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      579
#define TRAINER_TABITHA_MAGMA_HIDEOUT       580
#define TRAINER_DARCY                       581
#define TRAINER_MAXIE_MOSSDEEP              582
#define TRAINER_PETE                        583
#define TRAINER_ISABELLE                    584
#define TRAINER_ANDRES_1                    585
#define TRAINER_ANDRES_2                    586
#define TRAINER_JOSUE                       587
#define TRAINER_CAMRON                      588
#define TRAINER_CORY_1                      589
#define TRAINER_CORY_2                      590
#define TRAINER_CAROLINA                    591
#define TRAINER_ELIJAH                      592
#define TRAINER_CELIA                       593
#define TRAINER_BRYAN                       594
#define TRAINER_BRANDEN                     595
#define TRAINER_BRYANT                      596
#define TRAINER_SHAYLA                      597
#define TRAINER_KYRA                        598
#define TRAINER_JAIDEN                      599
#define TRAINER_ALIX                        600
#define TRAINER_HELENE                      601
#define TRAINER_MARLENE                     602
#define TRAINER_DEVAN                       603
#define TRAINER_JOHNSON                     604
#define TRAINER_MELINA                      605
#define TRAINER_BRANDI                      606
#define TRAINER_AISHA                       607
#define TRAINER_MAKAYLA                     608
#define TRAINER_FABIAN                      609
#define TRAINER_DAYTON                      610
#define TRAINER_RACHEL                      611
#define TRAINER_LEONEL                      612
#define TRAINER_CALLIE                      613
#define TRAINER_CALE                        614
#define TRAINER_MYLES                       615
#define TRAINER_PAT                         616
#define TRAINER_CRISTIN_1                   617
#define TRAINER_CRISTIN_2                   618
#define TRAINER_ANGELO                      619
#define TRAINER_DARIUS                      620
#define TRAINER_STEVEN                      621
#define TRAINER_ANABEL                      622
#define TRAINER_TUCKER                      623
#define TRAINER_SPENSER                     624
#define TRAINER_GRETA                       625
#define TRAINER_NOLAND                      626
#define TRAINER_LUCY                        627
#define TRAINER_BRANDON                     628
#define TRAINER_MARIELA                     629
#define TRAINER_ALVARO                      630
#define TRAINER_EVERETT                     631
#define TRAINER_RED                         632
#define TRAINER_LEAF                        633
#define TRAINER_DAD_ROUTE103_TREECKO        634
#define TRAINER_DAD_ROUTE103_TORCHIC        635
#define TRAINER_DAD_ROUTE103_MUDKIP         636


// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      637
#define MAX_TRAINERS_COUNT                  864
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
